algorithm: nce
save_dir: ./saved_models/nce/
save_name: nce-cifar100-er10-mem2000
resume: False
#load_path: ./saved_models/usb_cv//baseline_cifar100/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
num_log_iter: 200
num_eval_iter: 200
batch_size: 10
eval_batch_size: 16
num_labels: 40000
buffer_size: 2000
uratio: 1
ema_m: 0.0
img_size: 32
crop_ratio: 0.875
p_cutoff: 0.95
optim: AdamW
lr: 0.002
layer_decay: 0.5
momentum: 0.9
er_frequency: 10
split_num: 20
weight_decay: 0.0005
threshold: 0.2
amp: False
clip: 0.0
use_cat: True
net: vit_tiny_patch2_32
lambda_reg: 0.01
net_from_name: False
data_dir: ./data
dataset: cifar100
train_sampler: SequentialSampler
num_classes: 100
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10021
dist_backend: nccl
gpu: None
use_pretrain: True
pretrain_path: ./pretrained_models/vit_tiny_patch2_32_mlp_im_1k_32.pth
