algorithm: nce
save_dir: ./saved_models/nce/
save_name: nce_imagenet
resume: False
#load_path: ./saved_models/usb_cv//nce_cifar100/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
num_log_iter: 50
num_eval_iter: 50
batch_size: 3
eval_batch_size: 16
num_labels: 2000000
buffer_size: 100
uratio: 1
ema_m: 0.0
img_size: 224
crop_ratio: 0.875
p_cutoff: 0.95
optim: AdamW
lr: 0.0005
layer_decay: 0.5
momentum: 0.9
er_frequency: 500
split_num: 200
threshold: 0.2
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
net: vit_base_patch16_224
lambda_u: 1
lambda_reg: 0.01
net_from_name: False
data_dir: ./data
dataset: imagenet
train_sampler: SequentialSampler
num_classes: 1000
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10021
dist_backend: nccl
gpu: None
use_pretrain: True
pretrain_path: ./pretrained_models/mae_pretrain_vit_base.pth
