algorithm: baseline
save_dir: ./saved_models/baseline/eurosat/
save_name: baseline_eurosat/no_split_pretrain_no_er
resume: False
#load_path: ./saved_models/usb_cv//baseline_eurosat_40_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
#epoch: 200
num_log_iter: 40
num_eval_iter: 40
batch_size: 8
eval_batch_size: 16
er_frequency: 1000000
num_labels: 18000
split_num: 1
buffer_size: 500
uratio: 1
ema_m: 0.0
img_size: 32
crop_ratio: 0.875
optim: AdamW
lr: 1e-04
layer_decay: 1.0
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
net: vit_tiny_patch2_32
net_from_name: False
data_dir: ./data
dataset: eurosat
train_sampler: SequentialSampler
num_classes: 10
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10022
dist_backend: nccl
gpu: None
use_pretrain: True
pretrain_path: ./pretrained_models/vit_tiny_patch2_32_mlp_im_1k_32.pth
