algorithm: baseline
save_dir: ./saved_models/baseline/cifar10
save_name: baseline_cifar10/nopretrain_nosplit_noer
resume: False
#load_path: ./saved_models/usb_cv//baseline_cifar100/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
num_log_iter: 40
num_eval_iter: 40
batch_size: 8
eval_batch_size: 16
num_labels: 40000
buffer_size: 500
uratio: 1
ema_m: 0.0
img_size: 32
crop_ratio: 0.875
p_cutoff: 0.95
optim: AdamW
lr: 0.002
layer_decay: 0.5
momentum: 0.9
er_frequency: 100000
split_num: 1
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
net: vit_tiny_patch2_32
lambda_u: 1
net_from_name: False
data_dir: ./data
dataset: cifar10
train_sampler: SequentialSampler
num_classes: 10
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10021
dist_backend: nccl
gpu: None
use_pretrain: False
pretrain_path: ./pretrained_models/vit_tiny_patch2_32_mlp_im_1k_32.pth
